### ISSUE TITLE
Second _mbstok likely should be _mbstok_l

### ISSUE THREAD

**Issue by versat** [MicrosoftDocs/cpp-docs.de-de#18]
As the title suggests the second declaration of _mbstok likely should be the declaration for _mbstok_l.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1b3bc926-dabf-9acc-27ed-447707e971df
* Version Independent ID: 00ddc54e-c89f-843c-237a-20ae726d2021
* Content: [strtok, _strtok_l, wcstok, _wcstok_l, _mbstok, _mbstok_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/strtok-strtok-l-wcstok-wcstok-l-mbstok-mbstok-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #876](https://github.com/MicrosoftDocs/cpp-docs/issues/876) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @versat 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/876

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
