### ISSUE TITLE
Don't translate C++ Keywords into German

### ISSUE THREAD

**Issue by TimTalerJr** [MicrosoftDocs/cpp-docs.de-de#39]
Keywords of any programming language should not be translated at all. 

E. g.: false: "Verwenden Sie die bereichsbasierte **für** Anweisung zum Erstellen von Schleifen,..."
right: "Verwenden Sie die bereichsbasierte **for** Anweisung zum Erstellen von Schleifen, ..."
and further: "die über einen "Bereich" ausgeführt werden müssen, der als alles definiert ist, was Sie durchlaufen können"

It's a Google-Translation, but it is on point!

**Comment by srvbpigh** [comment]
Hello, @TimTalerJr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>,
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**Can you please provide the URL where you found this issue?**

Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @TimTalerJr , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

 **Could you please provide the URL where this issue was found?** 

Kind regards, 
Microsoft DOCS International Team

**Comment by TimTalerJr** [comment]
Hello, 

I found this issue on following websites: 

https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/cpp/range-based-for-statement-cpp.md


 

what is a copy of the site:

https://docs.microsoft.com/de-de/cpp/cpp/range-based-for-statement-cpp?view=vs-2019

 

which is a translation of:

https://docs.microsoft.com/en-us/cpp/cpp/range-based-for-statement-cpp?view=vs-2019

 

 

With regards

Andreas Kohlmann

(TimTalerJr on Github)

 

 

Gesendet: Mittwoch, 18. März 2020 um 10:33 Uhr
Von: "V-vafune" <notifications@github.com>
An: "MicrosoftDocs/cpp-docs.de-de" <cpp-docs.de-de@noreply.github.com>
Cc: TimTalerJr <AndreasLbg@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/cpp-docs.de-de] Don't translate C++ Keywords into German (#39)


 

Hello, @TimTalerJr ,

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

 Could you please provide the URL where this issue was found?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @TimTalerJr 

Thank you for your contribution.

Contributions on translation problems against machine-translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team
