### ISSUE TITLE
German translation of the page is broken.

### ISSUE THREAD

**Issue by sr1ch1** [MicrosoftDocs/cpp-docs.de-de#53]
Hello,
the german translation of the page is broken. (basic-string-class)
Typedefs are translated but they should not ("Zeichner", "Referenz")
Member functions are translated but they should not ("Persönlich", "löschen", "Vergleichbar"... "Beifahrer"?)
Parameter names are  translated but they should not ("erstes", "letztes", "abgeschrieben")
This makes the whole article unreadable in german.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b9fedc7b-0ebe-766c-9089-548293b3b08f
* Version Independent ID: 451f8367-d247-95fb-03ec-0f9195e165e1
* Content: [basic_string-Klasse](https://docs.microsoft.com/de-de/cpp/standard-library/basic-string-class?view=vs-2019)
* Content Source: [docs/standard-library/basic-string-class.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/standard-library/basic-string-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@sr1ch1 , thank you for letting us know. I've updated the page so that machine translation shouldn't be applied to function names, parameter names, etc.
The fix should be visible by the end of tomorrow (10/27/2020)
#please-close

**Comment by sr1ch1** [comment]
Looks fine. Thank you.

**Comment by lukoerfer** [comment]
> I've updated the page so that machine translation shouldn't be applied to function names, parameter names, etc.

Either this is still not working as intended or some parameters names are not correctly marked as such.

As an example, the reference on [`fopen_s` and `wfopen_s`](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/fopen-s-wfopen-s.md) lists some really weird values for the `mode` parameter:

While the translation of the original parameter `a` to `ein` (German for one) can be explained quite easily, I have no idea how the parameter `w` became `Löw` in the German translation, as this the name of the German national soccer team head coach. There are more weird values later in the article including `scher`, `Bund` and `Hymnen`.

**Comment by TylerMSFT** [comment]
@lukoerfer ,
This problem is pervasive throughout the CRT docs. I fixed the page you referred to, and it appears you are now referring to some new ones (fopen_s, wfopen_s). 
I believe many of these docs were written before the current machine translation system was put into use. I'll take a look at those two topic, but it'd be easier to track these if you open a new issue in the future for the ones you find.
Sorry you have to deal with this. I'll try to fix them as I find them. There isn't a global solution, unfortunately.

**Comment by lukoerfer** [comment]
@TylerMSFT
I did not report the original issue, but it seemed to me like the problems had the same cause, so I decided to comment on this existing issue. Sorry for the inconvenience, I'll report future problems in new issues.

**Comment by TylerMSFT** [comment]
@lukoerfer , no problem. I appreciate you bringing this to our attention.
I should have this fixed soon. Because we are heading into the weekend, look for the fix live by Tues, Nov 24.
Thanks again.

**Comment by TylerMSFT** [comment]
I've checked the fix into our system. Because it's the weekend, and a big here in the US next week, it may take longer than usual to go through the steps to get published.
I'm closing this in anticipation of my fixes addressing the problem you raised here.
Thanks again for bringing this to our attention.
